// class Autogenerated {
//   int? id;
//   String? divisionId;
//   String? name;
//   String? bnName;
//   String? lat;
//   String? long;
//   String? createdAt;
//   String? updatedAt;
//
//   Autogenerated(
//       {this.id,
//         this.divisionId,
//         this.name,
//         this.bnName,
//         this.lat,
//         this.long,
//         this.createdAt,
//         this.updatedAt}
//         );
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     divisionId = json['division_id'];
//     name = json['name'];
//     bnName = json['bn_name'];
//     lat = json['lat'];
//     long = json['long'];
//     createdAt = json['created_at'];
//     updatedAt = json['updated_at'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['division_id'] = this.divisionId;
//     data['name'] = this.name;
//     data['bn_name'] = this.bnName;
//     data['lat'] = this.lat;
//     data['long'] = this.long;
//     data['created_at'] = this.createdAt;
//     data['updated_at'] = this.updatedAt;
//     return data;
//   }
// }
//
//
//
//
//
